### ISSUE TITLE
Doesn't work for audio files (e.g. MP3)

### ISSUE THREAD

**Issue by Frosty-J** [zeroepoch/plotbitrate#26]
The README says it's "a script for plotting the bitrate of an audio or video stream over time" but I haven't had any luck with plotting audio as there's no frames for it to work with.

```
Progress: 100.0%
Traceback (most recent call last):
  File "/home/james/.local/bin/plotbitrate", line 8, in <module>
    sys.exit(main())
  File "/home/james/.local/lib/python3.10/site-packages/plotbitrate.py", line 661, in main
    peak, mean = add_area(
  File "/home/james/.local/lib/python3.10/site-packages/plotbitrate.py", line 583, in add_area
    offset = math.floor(frames_list[0].time)
IndexError: list index out of range
```

**Comment by zeroepoch** [comment]
@Frosty-J,
I don't believe I've actually tried a pure audio file, so I wonder if there is some assumption that `I` frames exist. Double checking that you used `--stream audio` option when you invoked the script?

**Comment by Frosty-J** [comment]
Using that fixed it, thanks.
